src/test/java/com/vaadin/ui/upload/UploadView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/11)

Remove commented out code from the demo source example

---

src/main/java/com/vaadin/ui/upload/receivers/FileBuffer.java
src/main/java/com/vaadin/ui/upload/receivers/FileFactory.java
src/main/java/com/vaadin/ui/upload/receivers/MultiFileBuffer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/20)

Fix javadocs for FileBuffers.

---

src/main/java/com/vaadin/flow/component/upload/FinishedEvent.java
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUploadFile.java
src/main/java/com/vaadin/flow/component/upload/ProgressUpdateEvent.java
src/main/java/com/vaadin/flow/component/upload/StartedEvent.java
src/main/java/com/vaadin/flow/component/upload/Upload.java
src/test/java/com/vaadin/flow/component/paper/dialog/GeneratedPaperDialog.java
src/test/java/com/vaadin/flow/component/upload/demo/UploadView.java

The part of the package rename #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/22)

Update imports due the package rename in the server module

---

src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUploadFile.java
src/test/java/com/vaadin/flow/component/upload/demo/UploadView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/23)

Update generated component and add lumo style to demos

---

pom.xml
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUploadFile.java
src/main/java/com/vaadin/flow/component/upload/Upload.java
src/test/java/com/vaadin/flow/component/upload/demo/UploadView.java
src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/29)

Update Upload with the lasted generated file. Remove paper-dialog dependency.

---

pom.xml
src/test/java/com/vaadin/flow/component/upload/demo/UploadView.java

renaming repository ids;
removing HtmlImport from component demo;
enable logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/31)

Using new webjars

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/35)

Fix Flow documentation link in README

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/36)

Fix the dependency conflict in platform

---

src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUploadFile.java
src/main/java/com/vaadin/flow/component/upload/Upload.java
src/test/java/com/vaadin/flow/component/paper/dialog/GeneratedPaperDialog.java

fix after vaadin/flow#3678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/38)

Update generated code

---

pom.xml
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/39)

Update webcomponent to 4.0.0-beta2

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/40)

Update progress bar version

---

src/main/java/com/vaadin/flow/component/upload/FailedEvent.java

Fixes #27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/43)

Correct javadocs for FailedEvent

---

pom.xml
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUploadFile.java
src/main/java/com/vaadin/flow/component/upload/Upload.java

Add two new APIs from the generated class
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/44)

Update webjars and generated code

---

src/main/java/com/vaadin/flow/component/upload/UploadI18N.java
src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java
src/main/java/com/vaadin/flow/component/upload/receivers/FileData.java
src/main/java/com/vaadin/flow/component/upload/receivers/FileFactory.java

Partial fix for vaadin/platform#173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/46)

Make classes serializable

---

pom.xml
src/test/java/com/vaadin/flow/component/upload/tests/UploadSerializableTest.java

Related vaadin/platform/issues/173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/47)

Add serialization test with problematic class excluded

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/49)

Update Readme on running the components

---

src/main/java/com/vaadin/flow/component/upload/Upload.java
src/test/java/com/vaadin/flow/component/upload/demo/UploadView.java
src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java

Add test.
Fix related to same issue with vaadin/vaadin-date-picker-flow#88 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/50)

Fix i18n setting for Upload

---

src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java

Related to #51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/52)

Add test case to check the console error

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/66)

Update webjars with Material Theme

---

src/test/java/com/vaadin/flow/component/upload/demo/UploadView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/73)

Turn off formatter for the long named demo

---

src/test/java/com/vaadin/flow/component/upload/demo/UploadView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/74)

Turn off formatter for the long named demo (#73)

---

src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java
src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUploadFile.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/83)

Update java wrapper to stable version

---

src/main/java/com/vaadin/flow/component/upload/UploadI18N.java

Make i18n fix backportable so that we have no API changes.
Closes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/90)

Fix i18n.units.size[unit] error

---

src/main/java/com/vaadin/flow/component/upload/FailedEvent.java
src/main/java/com/vaadin/flow/component/upload/FinishedEvent.java
src/main/java/com/vaadin/flow/component/upload/NoInputStreamEvent.java
src/main/java/com/vaadin/flow/component/upload/NoOutputStreamEvent.java
src/main/java/com/vaadin/flow/component/upload/ProgressListener.java
src/main/java/com/vaadin/flow/component/upload/ProgressUpdateEvent.java
src/main/java/com/vaadin/flow/component/upload/Receiver.java
src/main/java/com/vaadin/flow/component/upload/StartedEvent.java
src/main/java/com/vaadin/flow/component/upload/SucceededEvent.java
src/main/java/com/vaadin/flow/component/upload/Upload.java
src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java
src/main/java/com/vaadin/flow/component/upload/receivers/FileData.java
src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java
src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileMemoryBuffer.java

Working on another PR I've found many inconsistencies in this repo JavaDocs. With this PR I'm trying to fix those inconsistencies adopting the conventions I've seen in other Vaadin's repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/102)

Fix JavaDocs

---

src/main/java/com/vaadin/flow/component/upload/FailedEvent.java
src/main/java/com/vaadin/flow/component/upload/FinishedEvent.java
src/main/java/com/vaadin/flow/component/upload/NoInputStreamEvent.java
src/main/java/com/vaadin/flow/component/upload/NoOutputStreamEvent.java
src/main/java/com/vaadin/flow/component/upload/ProgressListener.java
src/main/java/com/vaadin/flow/component/upload/ProgressUpdateEvent.java
src/main/java/com/vaadin/flow/component/upload/Receiver.java
src/main/java/com/vaadin/flow/component/upload/StartedEvent.java
src/main/java/com/vaadin/flow/component/upload/SucceededEvent.java
src/main/java/com/vaadin/flow/component/upload/Upload.java
src/main/java/com/vaadin/flow/component/upload/receivers/AbstractFileBuffer.java
src/main/java/com/vaadin/flow/component/upload/receivers/FileData.java
src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java
src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileMemoryBuffer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/106)

Fix JavaDocs (#102)

---

src/main/java/com/vaadin/flow/component/upload/Upload.java

Should fix #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/110)

Fix: Call FinishEvent after upload finishes.

---

pom.xml
vaadin-upload-flow-demo/pom.xml
vaadin-upload-flow-integration-tests/pom.xml
vaadin-upload-flow-testbench/pom.xml
vaadin-upload-flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/116)

Update to next minor and Use flow 1.5-SNAPSHOT

---

pom.xml
vaadin-upload-flow-integration-tests/pom-bower-mode.xml
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUploadFile.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/128)

Add bower tests

---

vaadin-upload-flow-integration-tests/pom-bower-mode.xml

Should fix snapshot build step  `Fail if non-pinned dependencies found`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/129)

Pin dependency versions.

---

vaadin-upload-flow/pom.xml
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/130)

Update to latest versions.

---

vaadin-upload-flow-testbench/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/131)

Remove vaadin-components-testbench

---

pom.xml
vaadin-upload-flow-integration-tests/pom-bower-mode.xml
vaadin-upload-flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/137)

Fix upload snapshot test build

---

vaadin-upload-flow/pom.xml
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/140)

Bump versions, update WC dependency to 4.2.2

---

vaadin-upload-flow-demo/src/main/java/com/vaadin/flow/component/upload/demo/UploadView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/133)

fix an obvious error

---

.gitignore
pom.xml
vaadin-upload-flow-demo/pom.xml
vaadin-upload-flow-integration-tests/pom-bower-mode.xml
vaadin-upload-flow-integration-tests/pom.xml
vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/UploadView.java
vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
vaadin-upload-flow-testbench/pom.xml
vaadin-upload-flow/pom.xml
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/UploadsFinishedEvent.java

Fixes #134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/144)

Uploads finished event

---

vaadin-upload-flow-demo/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/150)

Only use flow-maven-plugin when packaging is war

---

vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/UploadView.java
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/AllFinishedEvent.java
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Renamed: to addAllFinishedListener
Fixes #151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/152)

Fire all finished event on cancel of the last upload

---

vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Connected to https://github.com/vaadin/components-team-tasks/issues/483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/153)

Update exception phrase

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-upload-flow/156)

Bump flow-component-base and remove flow.version

---

vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java

Fixes: Method setUploadButton() works differently as documented 

---

vaadin-upload-flow-demo/src/main/java/com/vaadin/flow/component/upload/demo/UploadView.java

Fixes https://github.com/vaadin/vaadin-upload-flow/issues/124 https://github.com/vaadin/90min-dx-tasks/issues/146

Add helper methods to examples

---

vaadin-upload-flow-demo/src/main/java/com/vaadin/flow/component/upload/demo/UploadView.java

This issue is for users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files

Adding missing method to Vaadin Upload demos

---

pom.xml
vaadin-upload-flow-demo/pom.xml
vaadin-upload-flow-integration-tests/pom-bower-mode.xml
vaadin-upload-flow-integration-tests/pom.xml
vaadin-upload-flow-testbench/pom.xml
vaadin-upload-flow/pom.xml
vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/GeneratedVaadinUpload.java

* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534

Bump versions for V14.3

---

vaadin-upload-flow-demo/src/main/java/com/vaadin/flow/component/upload/demo/UploadView.java

Fixes https://github.com/vaadin/vaadin-upload-flow/issues/72

Improve Upload demo
